### ISSUE TITLE
Incorrect Google Analytics Tag

### ISSUE THREAD

**Issue by yashvesikar** [ilyasabdulrahman/Portfolio#1]
Hey it looks like you forgot to remove my Google Analytics code from your source code. 

If you could remove [the following tag](https://github.com/ilyasabdulrahman/Portfolio/blob/9278a3aa06050286dff7ba66180c55ecc35b278e/index.html#L7-L15) that would be awesome!

**Comment by ilyasabdulrahman** [comment]
Yep, got it!
